### ISSUE TITLE
Proposal: allow to pass a few chat ids

### ISSUE THREAD

**Issue by Alkalit** [sashgorokhov/python-telegram-handler#24]
So a bot could notify multiple people

**Comment by JosXa** [comment]
Let me do the hard work of typing this out for you:

It would be nice if `bot.send_*` accepted an iterable for the `chat_id(s)` parameter in order to allow for sending broadcasts. It should abstract away dealing with flood waits and possible "could not contact" exceptions and thus make it easier for developers to reach a broad audience.

**Comment by Alkalit** [comment]
@JosXa well, I overcame the waiting problem by using combination of 'logging.handlers.QueueHandler' and `QueueListener`. So I think it is really not a problem. But yeah, you are right about disconnects and other network problems. So currently to solve this I made a channel where invited all other participants.

**Comment by JosXa** [comment]
What does the logging module have to do with it? :O
