### ISSUE TITLE
Memory leak when root logger used with debug level

### ISSUE THREAD

**Issue by MelomanCool** [sashgorokhov/python-telegram-handler#6]
Code to reproduce:
```python
import logging
from telegram_handler import TelegramHandler

root_logger = logging.getLogger()
root_logger.setLevel(logging.DEBUG)
handler = TelegramHandler('TOKEN', 'CHAT_ID')
root_logger.addHandler(handler)

root_logger.info('test')
```

**Comment by sashgorokhov** [comment]
How did you detected it?

**Comment by MelomanCool** [comment]
Well, I was using a [similar](http://stackoverflow.com/a/15729700/6879054) setup to log from modules of my app. At first, I've used [logging.basicConfig](https://docs.python.org/2/library/logging.html#logging.basicConfig), which is creating a StreamHandler. 
But when I've changed the handler to TelegramHandler, as shown in the above example, my app started to eat up all available memory.

**Comment by MelomanCool** [comment]
Looks like I've managed to find the cause of the issue.
The root logger is handled by TelegramHandler. And every other logger is a child of the root one, so all of them are also handled by TelegramHandler, which is good. But, since there is also a logger in the TelegramHandler, it starts to log to itself, creating infinite recursion.

**Comment by sashgorokhov** [comment]
So, I must set the TelegramHandler logger level to INFO, so that it wont propagate to root logger unless explicitly configured. In default setup, when logger is created, its level is set to NOTSET, `which causes all messages to be processed when the logger is the root logger, or delegation to the parent when the logger is a non-root logger`. This must break the recursion loop.
